name: Secret

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Use secret variable
      env:
        SECRET: ${{ secrets.SECRET_VARIABLE }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo ${SECRET}
        echo ${GITHUB_TOKEN}
