name: Test

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  services:
    name: services test
    runs-on: ubuntu-latest
    services:
      nginx:
        image: nginx
        ports:
        - 8080:80
      mysql:
        image: mysql
        ports:
        - 3306
    steps:
    - name: mysql port
      run: echo ${PORT}
      env:
        PORT: ${{ job.services.mysql.ports['3306'] }}
    - name: curl
      run: curl http://localhost:8080/

  os:
    name: test os info
    runs-on: ubuntu-latest
    steps:
    - name: os info
      run: |
        cat /proc/cpuinfo
        ls -lah /
        free -h
        ip a s
        curl -s https://domains.google.com/checkip
        date
        pwd

  docker:
    name: docker test
    runs-on: ubuntu-latest
    steps:
    - name: docker test
      uses: docker://alpine:latest
      with:
        args: echo test

  expression:
    name: expression test
    runs-on: ubuntu-latest
    steps:
    - name: if
      if: github.event_name == 'push'
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
