name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      nginx:
        image: nginx
        ports:
        - 8080:80
      mysql:
        image: mysql
        ports:
        - 3306
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: list file
      run: |
        ls -lah /
    - name: os
      run: |
        cat /proc/cpuinfo
        free -h
        ip a s
    - name: fs test
      run: |
        pwd
        date > ${HOME}/date
    - name: fs test2
      run: cat ${HOME}/date
    - name: docker test
      uses: docker://alpine:latest
      with:
        args: echo test
    - name: mysql port
      run: echo ${PORT}
      env:
        PORT: ${{ job.services.mysql.ports['3306'] }}
    - name: curl
      run: curl http://localhost:8080/
