name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: list file
      run: |
        ls -lah /
    - name: os
      run: |
        cat /proc/cpuinfo
        cat /proc/meminfo
        cat /proc/partitions
        cat /proc/loadavg
        cat /proc/stat
    - name: fs test
      run: |
        pwd
        date > ${HOME}/date
        date > /github/date
    - name: fs test2
      run: cat ${HOME}/date
    - name: net test
      run: |
        curl -o ${HOME}/hugo.tar.gz -L "https://github.com/gohugoio/hugo/releases/download/v0.57.2/hugo_extended_0.57.2_Linux-64bit.tar.gz"
